#datasets:
#  vizwiz:
#    data_type: images
#    build_info:
#      image_path: /cluster/scratch/jiezcao/jiameng/dataset/vizwiz/train
#      annotations: /cluster/scratch/jiezcao/jiameng/dataset/vizwiz/train.json # ann_path
datasets:
  vizwiz:
    data_dir: /nfs/data2/hewei/dataset/
    data_type: images # [images|videos|features]

    build_info:
      annotations:
        train:
          url:
              - https://vizwiz.cs.colorado.edu/VizWiz_final/vqa_data/Annotations/train.json
          storage:
              - /nfs/data2/hewei/dataset/vizwiz/train.json

      images:
          storage: /nfs/data2/hewei/dataset/vizwiz/