model:
  arch: minigpt4
  model_type: pretrain_vicuna0

  max_txt_len: 160
  end_sym: "###"
  prompt_path: "prompts/alignment.txt"
  prompt_template: '###Human: {} ###Assistant: '
  ckpt: "/cluster/scratch/jiezcao/jiameng/minigpt_model/prerained_minigpt4_7b.pth"


datasets:
  ok_vqa:
    batch_size: 6
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 3e-5
  min_lr: 1e-5
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 10
  iters_per_epoch: 200
  num_workers: 4
  warmup_steps: 200

  seed: 42
  output_dir: "/cluster/scratch/jiezcao/jiameng/minigpt_model/save_ckpt/ok/adalink/"

  amp: True
  resume_ckpt_path:  null
#  resume_ckpt_path: /cluster/scratch/jiezcao/jiameng/minigpt_model/save_ckpt/ok/adalink/20240215235/checkpoint_37.pth

  evaluate: False
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: False
  job_name: minigpt4_ok_adalink