model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 500
  end_sym: "</s>"
  low_resource: False
  prompt_template: '[INST] {} [/INST]'
  llama_model: "/cluster/scratch/jiezcao/jiameng/minigpt_model/vicuna7b/"#TODO
#  ckpt: "/cluster/scratch/jiezcao/jiameng/minigpt_model/save_ckpt/gqa/20240212084/checkpoint_4.pth"
  ckpt: "/cluster/scratch/jiezcao/jiameng/minigpt_model/save_ckpt/gqa/20240214184/checkpoint_9.pth"
  lora_r: 64
  lora_alpha: 16


datasets:
  gqa:
    vis_processor:
      train:
        name: "blip2_image_eval"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

evaluation_datasets:
  gqa:
    eval_file_path: /cluster/scratch/jiezcao/jiameng/dataset/gqa/
    img_path: /cluster/scratch/jiezcao/jiameng/dataset/gqa/images/train/
    max_new_tokens: 20
    batch_size: 10

run:
  task: image_text_pretrain
  name: minigptv2_evaluation
#  save_path: "/cluster/scratch/jiezcao/jiameng/minigpt_model/save_ckpt/gqa/20240212084/"
  save_path: "/cluster/scratch/jiezcao/jiameng/minigpt_model/save_ckpt/gqa/20240214184/"