datasets:
  ocrvqa:
    data_type: images
    build_info:
      image_path: /cluster/scratch/jiezcao/jiameng/dataset/ocrvqa/images
      ann_path: /cluster/scratch/jiezcao/jiameng/dataset/ocrvqa/dataset.json